Controllers/DepositController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NRDCL.Models;
using NRDCL.Models.Common;

namespace NRDCL.Controllers
{
    public class DepositController : Controller
    {
        private readonly IDepositService  depositService;
        public DepositController(IDepositService service)
        {
            depositService = service;
        }

        // GET: Deposits/Details/5
        public async Task<IActionResult> Details(string customerID)
        {
            if (customerID.Equals(null))
            {
                return new NotFoundResult();
            }
            var deposit = await depositService.GetDepositDetails(customerID);
            if (deposit == null)
            {
                return new NotFoundResult();
            }
            return View(deposit);
        }

        // GET: Deposits/Create
        public IActionResult Create()
        {
            var depositList =  depositService.GetDepositList();
            ViewBag.Deposits = depositList.Result;
            return View();
        }

        // POST: Deposits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerID,LastAmount")] Deposit deposit)
        {
            if (ModelState.IsValid)
            {
                Task<ResponseMessage> responseMessage = depositService.SaveDeposit(deposit);
                if (responseMessage.Result.Status == false)
                {
                    ModelState.AddModelError(responseMessage.Result.MessageKey, responseMessage.Result.Text);
                    return View(deposit);
                }
                ViewBag.Result = CommonProperties.saveSuccessMsg;
                ModelState.Clear();
                deposit = new Deposit();
            }
            var depositList = depositService.GetDepositList();
            ViewBag.Deposits = depositList.Result;
            return View(await Task.FromResult(deposit));
        }
    }
}

Controllers/OrderController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NRDCL.Models;
using NRDCL.Models.Common;

namespace NRDCL.Controllers
{
    public class OrderController : Controller
    {
        #region private variables
        private readonly ISiteService siteService;
        private readonly IOrderService orderService;
        private readonly IProductService productService;
        #endregion

        #region Constructor Injection
        public OrderController(ISiteService service, IOrderService order, IProductService product)
        {
            siteService = service;
            orderService = order;
            productService = product;
        }
        #endregion
        #region public methods
        /// <summary>
        /// Get order detail
        /// </summary>
        /// <param name="orderId"></param>
        /// <returns></returns>
        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int orderId)
        {
            if (orderId == 0)
            {
                return new NotFoundResult();
            }
            var order = await orderService.GetOrderDetails(orderId);
            if (order == null)
            {
                return new NotFoundResult();
            }
            return View(order);
        }

        /// <summary>
        /// Create order
        /// </summary>
        /// <returns></returns>
        // GET: Orders/Create
        public IActionResult Create(int? orderId)
        {
            Task<List<Order>> orderList = orderService.GetOrderList();
            ViewBag.Orders = orderList.Result;
            var order = new Order();
            List<SelectListItem> siteList = new List<SelectListItem>()
                {
                new SelectListItem
                {
                    Value = null,
                    Text = " "
                }
            };
            if (orderId!=null && orderId!=0) {
                order = orderService.GetOrderDetails((int)orderId).Result;
                order.CMDstatus = "M";

                 siteList = siteService.GetSiteList().Result.Where(s => s.CitizenshipID.Equals(order.CustomerID)).Select(s => new SelectListItem()
                {
                    Value = s.SiteId.ToString(),
                    Text = s.SiteName
                }).ToList();
                order.SiteList = siteList;
            }
            order.SiteList = siteList;
            var productList = productService.GetProductList();
            ViewData["ProductList"] = new SelectList(productList.Result, "ProductId", "ProductName");
            return View(order);
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("CMDstatus,OrderID,CustomerID,SiteID,ProductID,Quantity,OrderAmount")] Order order)
        {
            Task<List<Order>> orderList = orderService.GetOrderList();
            ViewBag.Orders = orderList.Result;
            ResponseMessage responseMessage = null;
            IEnumerable<SelectListItem> siteList = siteService.GetSiteList().Result.Where(s => s.CitizenshipID.Equals(order.CustomerID)).Select(s => new SelectListItem()
            {
                Value = s.SiteId.ToString(),
                Text = s.SiteName
            }).ToList();
            order.SiteList = siteList;

            var productList = productService.GetProductList();
            ViewData["ProductList"] = new SelectList(productList.Result, "ProductId", "ProductName");
            if (ModelState.IsValid)
            {
                responseMessage = orderService.SaveOrder(order);
                if (responseMessage.Status == false)
                {
                    ModelState.AddModelError(responseMessage.MessageKey, responseMessage.Text);
                    return View(order);
                }
                ViewBag.Result = responseMessage.Text;
                ModelState.Clear();
            }
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int orderId)
        {
            if (orderId == 0)
            {
                return new NotFoundResult();
            }
            var order = await orderService.GetOrderDetails(orderId);
            if (order == null)
            {
                return new NotFoundResult();
            }
            IEnumerable<SelectListItem> siteList = siteService.GetSiteList().Result.Where(s => s.CitizenshipID.Equals(order.CustomerID)).Select(s => new SelectListItem()
            {
                Value = s.SiteId.ToString(),
                Text = s.SiteName
            }).ToList();
            order.SiteList = siteList;

            var productList = productService.GetProductList();
            ViewData["ProductList"] = new SelectList(productList.Result, "ProductId", "ProductName");
            return RedirectToAction("Create", new {orderId});
           // return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Edit(int orderId, [Bind("OrderID,CustomerID,SiteID,ProductID,Quantity,OrderAmount")] Order order)
        {
            IEnumerable<SelectListItem> siteList = siteService.GetSiteList().Result.Where(s => s.CitizenshipID.Equals(order.CustomerID)).Select(s => new SelectListItem()
            {
                Value = s.SiteId.ToString(),
                Text = s.SiteName
            }).ToList();
            order.SiteList = siteList;

            var productList = productService.GetProductList();
            ViewData["ProductList"] = new SelectList(productList.Result, "ProductId", "ProductName");
            if (orderId != order.OrderID)
            {
                return new NotFoundResult();
            }
            if (ModelState.IsValid)
            {
                ResponseMessage responseMessage = orderService.SaveOrder(order);
                if (responseMessage.Status == false)
                {
                    ModelState.AddModelError(responseMessage.MessageKey, responseMessage.Text);
                    return View(order);
                }
                ViewBag.Result = responseMessage.Text;
                ModelState.Clear();
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int OrderID)
        {
            if (OrderID == 0)
            {
                return new NotFoundResult();
            }
            var order = await orderService.GetOrderDetails(OrderID);
            if (order == null)
            {
                return new NotFoundResult();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int OrderID)
        {
            var responseMessage = await orderService.DeleteOrder(OrderID);
            return RedirectToAction(nameof(Create));
        }

        /// <summary>
        /// Get site dropdown based on customerID
        /// </summary>
        /// <param name="customerID"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> GetSiteByCustomerId(string customerID)
        {
            IEnumerable<SelectListItem> siteList= siteService.GetSiteList().Result.Where(s => s.CitizenshipID.Equals(customerID)).Select(s => new SelectListItem()
            {
                Value = s.SiteId.ToString(),
                Text = s.SiteName
            }).ToList();
            //var siteList = 
            var filteredSiteList = new SelectList(siteList, "Value", "Text");
            return Json(await Task.Run(()=> filteredSiteList));
            //return Json(filteredSiteList);
        }

        /// <summary>
        /// Calculates order amount
        /// </summary>
        /// <param name="order"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> CalculateOrderAmount(Order order)
        {
            Task<decimal> orderAmount= orderService.CalculateOrderAmount(order);
            return Json(await orderAmount);
        }
        #endregion
    }
}

Controllers/ProductController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NRDCL.Models;
using NRDCL.Models.Common;

namespace NRDCL.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly IProductService productService;
        public ProductController(IProductService service)
        {
            productService = service;
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int productID)
        {
            if (productID == 0)
            {
                return NotFound();
            }
            var product = await productService.GetProductDetails(productID);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create(int? productId)
        {
            Product product = null;
            if (productId != null && productId!=0)
            {
                product = productService.GetProductDetails((int)productId).Result;
                product.CMDstatus = "M";
            }
            var productList =  productService.GetProductList();
            ViewBag.Products = productList.Result;
            return View(product);
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CMDstatus,ProductId,ProductName,PricePerUnit,TransportRate")] Product product)
        {
            if (ModelState.IsValid)
            {

                ResponseMessage responseMessage = null;
                if (!string.IsNullOrEmpty(product.CMDstatus) && product.CMDstatus.Equals("M"))
                {
                    responseMessage = await productService.UpdateProduct(product);
                }
                else
                {
                    responseMessage = await productService.SaveProduct(product);
                }
                var productList = productService.GetProductList();
                ViewBag.Products = productList.Result;
                if (responseMessage.Status == false)
                {
                    ModelState.AddModelError(responseMessage.MessageKey, responseMessage.Text);
                    return View(product);
                }
                ViewBag.Result = responseMessage.Text;
                ModelState.Clear();
                product = new Product();
            }
            return View(await Task.FromResult(product));
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int productId)
        {
            if (productId == 0)
            {
               return new NotFoundResult();
            }
            var product = await productService.GetProductDetails(productId);
            if (product == null)
            {
                return new NotFoundResult();
            }
            return RedirectToAction("Create", new { productId });
        }
    }
}

Controllers/SiteController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NRDCL.Models;
using NRDCL.Models.Common;

namespace NRDCL.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SiteController : Controller
    {
        private readonly ISiteService siteService;

        public SiteController(ISiteService service)
        {
            siteService = service;
        }

        // GET: Sites/Details/5
        public async Task<IActionResult> Details(int siteId)
        {
            if (siteId == 0)
            {
                return NotFound();
            }
            var site = await siteService.GetSiteDetails(siteId);
            if (site == null)
            {
                return NotFound();
            }

            return View(site);
        }

        // GET: Sites/Create
        public IActionResult Create(int? siteId)
        {
            Site site = null;
            if (siteId!=null && siteId != 0) {
                site = siteService.GetSiteDetails((int)siteId).Result;
                site.CMDstatus = "M";
            }
            var siteList = siteService.GetSiteList();
            ViewBag.Sites = siteList.Result;
            return View(site);
        }

        // POST: Sites/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CMDstatus,SiteId,CitizenshipID,SiteName,DistanceFrom")] Site site)
        {
            if (ModelState.IsValid)
            {
                ResponseMessage responseMessage = null;
                if (!string.IsNullOrEmpty(site.CMDstatus) && site.CMDstatus.Equals("M"))
                {
                    responseMessage = await siteService.UpdateSite(site);
                }
                else
                {
                    responseMessage = await siteService.SaveSite(site);
                }
                var siteList = siteService.GetSiteList();
                ViewBag.Sites = siteList.Result;
                if (responseMessage.Status == false)
                {
                    ModelState.AddModelError(responseMessage.MessageKey, responseMessage.Text);
                    return View(site);
                }
                ViewBag.Result = responseMessage.Text;
                ModelState.Clear();
                site = new Site();
            }
            
            return View(await Task.FromResult(site));
        }

        // GET: Sites/Edit/5
        public async Task<IActionResult> Edit(int siteId)
        {
            if (siteId == 0)
            {
                return NotFound();
            }
            var site = await siteService.GetSiteDetails(siteId);
            if (site == null)
            {
                return NotFound();
            }
            return RedirectToAction("Create", new { siteId });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"] - NRDCL</title>
    <link href="~/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/bootstrap/css/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/sbadmin/css/sb-admin-2.css" rel="stylesheet" />
    <link href="~/css/sweetalert.css" rel="stylesheet" />
    <link href="~/css/jquery.dataTables.css" rel="stylesheet" />
</head>
<body>
    <div id="wrapper">
        <nav id="navHeader" class="navbar navbar-default navbar-static-top" role="navigation">
            <div class="navbar-header">
                <div class="form-group">
                    <div class="col-md-2">
                        <img style="padding:0px 0px 0px 0px;" src="~/images/Logo.png" />
                    </div>
                    <div class="col-md-10">
                        <p style="margin-left: 25%" class="headerTxt">NRDCL Project</p>
                    </div>
                </div>
                <div class=""></div>
            </div>
            <div class="nav navbar-top-links navbar-right">
                <ul class="navbar-nav">
                    <partial name="_LoginInfo" />
                </ul>
            </div>
            <br>
            <br>
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav nav-pills nav-stacked">
                        <li class="">
                            <a class="" asp-controller="Home" asp-action="Index" style="background-color: #004a80;color: #ffffff !important;"><i class="fa fa-home"></i>&nbsp;HOME</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li>
                                <a asp-controller="Administration" asp-action="CreateRole"><i class="glyphicon glyphicon-lock fa-fw"></i>&nbsp;&nbsp;Create Role</a>
                            </li>
                        }
                        <li>
                            <a asp-controller="Customer" asp-action="Create"><i class="glyphicon glyphicon-user"></i>&nbsp;&nbsp;Customer</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li>
                                <a asp-area="" asp-controller="Site" asp-action="Create"><i class="glyphicon glyphicon-briefcase"></i>&nbsp;&nbsp;Site</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li>
                                <a asp-area="" asp-controller="Product" asp-action="Create"><i class="glyphicon glyphicon-cog"></i>&nbsp;&nbsp;Product</a>
                            </li>
                        }
                        <li>
                            <a asp-area="" asp-controller="Deposit" asp-action="Create"><i class="glyphicon glyphicon-piggy-bank"></i>&nbsp;&nbsp;Deposit</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Order" asp-action="Create"><i class="glyphicon glyphicon-cog"></i>&nbsp;&nbsp;Order</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Report" asp-action="Index"><i class="glyphicon glyphicon-briefcase"></i>&nbsp;&nbsp;Report</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
        <div id="page-wrapper">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - NRDCL - Thimphu Techpark Limited
            </div>
        </footer>

    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/sweetalert.min.js"></script>
    <script src="~/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LoginInfo.cshtml
@using NRDCL.Models.Acc
@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> _signInManager

    @if (_signInManager.IsSignedIn(User))
    {
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                <label>Welcome::</label>
                <i class="fa fa-user-md fa-fw"></i> 
                <label> @User.FindFirst("UserFirstName").Value</label>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" asp-action="Logout" asp-controller="Account"><i class="fa fa-power-off"></i> Logout</a><br /><br />
                <a class="dropdown-item" asp-action="ChangePassword" asp-controller="Account">
                    <i class="fa fa-key icon"></i>
                    Change Password
                </a>
            </div>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="btn btn-outline-primary" asp-area="" asp-controller="Account" asp-action="Signin" asp-route-returnUrl="@Context.Request.Path"><i class="fa fa-user-md fa-fw"></i>Login</a>
            <a class="btn" asp-area="" asp-controller="Account" asp-action="Signup">Register</a>
        </li>
    }